name: loxia
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqlite3: ^2.9.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.3
  source_gen: ^4.1.0
  analyzer: ^8.4.1
  build: ^4.0.2
